CREATE TABLE CLIENT(
	client_id NUMBER PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	telephone VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE ADDRESS(
    street VARCHAR(150) NOT NULL,
	postcode VARCHAR(5) NOT NULL,
	city VARCHAR(100) NOT NULL,
	country VARCHAR(100) NOT NULL
);

CREATE TABLE ORDERS(
    number VARCHAR(10) PRIMARY KEY,
	delivery_address INTEGER NOT NULL,
	pilotes INTEGER NOT NULL,
	order_total DOUBLE NOT NULL,
	creation_date DATETIME NOT NULL
);
