spring:
  application:
    name: PilotesApplication
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MiHikariPool

  h2:
    console:
      enabled: true
    
mybatis:
  type-aliases-package: com.tui.proof.adapters.model

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs


com:
  tui:
    proof:
      qtyValues: [ 5, 10, 15 ]
      price: 1.33
      maxUpdateTime: 5
